import { Platform } from "react-native";

const primaryColorLight = "#0a7ea4";
const primaryColorDark = "#ffffff";

const tintColorLight = primaryColorLight;
const tintColorDark = primaryColorDark;

export const Colors = {
  light: {
    text: "#11181C",
    background: "#ffffff",
    primary: primaryColorLight,
    tint: tintColorLight,
    icon: "#687076",
    tabIconDefault: "#687076",
    tabIconSelected: tintColorLight,
    transparent: "transparent",
    white: "#FFFFFF",
    splashBackground: "#EFEFEF",
    splashRipple: "#2E6FBE",
    splashCircle: "#2E6FBE",
    splashShadow: "#1A4F8A",
    splashRingTrack: "rgba(140, 200, 255, 0.35)",
    splashRingArc: "rgba(255,255,255,0.9)",
    loginScreenBackground: "#D8DBE0",
    loginCardBackground: "#EDEDEF",
    loginHeaderGradientStart: "#246AB3",
    loginHeaderGradientEnd: "#3898EA",
    loginPlaceholder: "#A8A8A8",
    loginTabBorder: "#317ED4",
    loginTabBackground: "#EEF4FA",
    loginTabActiveBackground: "#2D74C3",
    loginTabText: "#2E6DB7",
    loginTabActiveText: "#FFFFFF",
    loginInputBorder: "#4B92DF",
    loginInputBackground: "#F3F4F6",
    loginInputText: "#1C2F44",
    loginError: "#D84040",
    loginCheckboxBorder: "#6EA7E6",
    loginCheckboxBackground: "#FFFFFF",
    loginCheckboxFill: "#2D74C3",
    loginUtilityText: "#5D6A79",
    loginHintText: "#8091A4",
    loginOrText: "#111111",
    socialFacebook: "#1B74E4",
    socialInstagram: "#F56040",
    socialGoogle: "#EA4335",
    dashboardScreenBackground: "#2C6EB8",
    dashboardHeaderBackground: "#F3F5F9",
    dashboardHeaderText: "#FFFFFF",
    dashboardSectionCardBackground: "#FFFFFF",
    dashboardSubtleText: "#D8E8FF",
    dashboardCategoryBubble: "#7CB0E6",
    dashboardCategoryIcon: "#2C6EB8",
    dashboardBottomBarBackground: "#8CC2F4",
    dashboardBottomIcon: "#2A66AB",
    dashboardBottomIconActive: "#1D4E88",
    dashboardSosButton: "#2F73C2",
    dashboardSosText: "#E7F2FF",
    dashboardShadow: "rgba(14, 56, 106, 0.24)",
    petDetailsSheetBackground: "#A4C7EE",
    petDetailsSurface: "#93B9E3",
    petDetailsTextPrimary: "#1E4E87",
    petDetailsTextSecondary: "#2B5F98",
    petDetailsOutline: "#2C6EB8",
    petDetailsActionBarBackground: "#EDEEEF",
    petDetailsActionIcon: "#2C6EB8",
    petDetailsAdoptButtonBackground: "#2C6EB8",
    petDetailsAdoptButtonText: "#FFFFFF",
  },
  dark: {
    text: "#ECEDEE",
    background: "#151718",
    primary: primaryColorDark,
    tint: tintColorDark,
    icon: "#9BA1A6",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: tintColorDark,
    transparent: "transparent",
    white: "#FFFFFF",
    splashBackground: "#151718",
    splashRipple: "#2E6FBE",
    splashCircle: "#2E6FBE",
    splashShadow: "#0D2C4D",
    splashRingTrack: "rgba(140, 200, 255, 0.35)",
    splashRingArc: "rgba(255,255,255,0.9)",
    loginScreenBackground: "#0F1318",
    loginCardBackground: "#151B23",
    loginHeaderGradientStart: "#1E4D82",
    loginHeaderGradientEnd: "#2E6FBE",
    loginPlaceholder: "#8A94A3",
    loginTabBorder: "#3E6EAA",
    loginTabBackground: "#1A2330",
    loginTabActiveBackground: "#2D74C3",
    loginTabText: "#A8C8F1",
    loginTabActiveText: "#FFFFFF",
    loginInputBorder: "#3D6390",
    loginInputBackground: "#111923",
    loginInputText: "#E6EEF7",
    loginError: "#FF6B6B",
    loginCheckboxBorder: "#5A87B8",
    loginCheckboxBackground: "#101722",
    loginCheckboxFill: "#4B92DF",
    loginUtilityText: "#B6C2D0",
    loginHintText: "#8EA0B7",
    loginOrText: "#ECEDEE",
    socialFacebook: "#1B74E4",
    socialInstagram: "#F56040",
    socialGoogle: "#EA4335",
    dashboardScreenBackground: "#2C6EB8",
    dashboardHeaderBackground: "#F3F5F9",
    dashboardHeaderText: "#FFFFFF",
    dashboardSectionCardBackground: "#FFFFFF",
    dashboardSubtleText: "#D8E8FF",
    dashboardCategoryBubble: "#7CB0E6",
    dashboardCategoryIcon: "#2C6EB8",
    dashboardBottomBarBackground: "#8CC2F4",
    dashboardBottomIcon: "#2A66AB",
    dashboardBottomIconActive: "#1D4E88",
    dashboardSosButton: "#2F73C2",
    dashboardSosText: "#E7F2FF",
    dashboardShadow: "rgba(14, 56, 106, 0.24)",
    petDetailsSheetBackground: "#A4C7EE",
    petDetailsSurface: "#93B9E3",
    petDetailsTextPrimary: "#1E4E87",
    petDetailsTextSecondary: "#2B5F98",
    petDetailsOutline: "#2C6EB8",
    petDetailsActionBarBackground: "#EDEEEF",
    petDetailsActionIcon: "#2C6EB8",
    petDetailsAdoptButtonBackground: "#2C6EB8",
    petDetailsAdoptButtonText: "#FFFFFF",
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  android: {
    sans: "sans-serif",
    serif: "serif",
    rounded: "sans-serif-rounded",
    mono: "monospace",
  },
  default: {
    sans: "sans-serif",
    serif: "serif",
    rounded: "sans-serif",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});

export const RoundedFontFamily = Fonts?.rounded ?? "sans-serif";
