import type {
  VeterinaryClinicFilter,
  VeterinaryClinicItem,
} from "@/features/veterinary/veterinary.types";

type VeterinaryFilterOption = {
  key: VeterinaryClinicFilter;
  label: string;
};

export const VETERINARY_ASSETS = {
  backIcon: require("../../assets/images/back-icon.png"),
  clinicPlaceholder: require("../../assets/images/veterinary-default-icon.png"),
} as const;

export const VETERINARY_FILTER_OPTIONS: VeterinaryFilterOption[] = [
  { key: "all", label: "All Clinics" },
  { key: "popular", label: "Popular" },
  { key: "recommended", label: "Recommended" },
];

const createDefaultClinicMedia = (clinicId: string) => [
  {
    id: `${clinicId}-media-photo-1`,
    type: "photo" as const,
  },
  {
    id: `${clinicId}-media-video-1`,
    type: "video" as const,
  },
  {
    id: `${clinicId}-media-photo-2`,
    type: "photo" as const,
  },
];

export const VETERINARY_CLINICS_MOCK_DATA: VeterinaryClinicItem[] = [
  {
    id: "vet-clinic-1",
    name: "BL Pet Shop & Salon",
    services: "Veterinary Clinic, Grooming & Pet Store",
    clinicType: "Store",
    category: "Pet Services",
    rating: 4.9,
    reviewCount: 503,
    address:
      "In SM Pampanga, Jose Abad Santos Ave, San Fernando, 2000 Pampanga, Philippines",
    distanceKm: 13.8,
    openingHours: "10 Am - 9 Pm",
    phone: "+63 927 010 2024",
    description:
      "Indulge in a blissful sanctuary for your beloved furry companion at BL Pet Shop & Salon, where exceptional veterinary care luxurious grooming, and an array of pet supplies converge. Our compassionate and highly skilled staff, led by the expert hands of Kuya Rex, will pamper and nurture your pet, ensuring their well-being and boundless joy.",
    latitude: 15.044613,
    longitude: 120.688598,
    media: createDefaultClinicMedia("vet-clinic-1"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: true,
    isRecommended: true,
  },
  {
    id: "vet-clinic-2",
    name: "San Fernando Animal Care Center",
    services: "Veterinary Consultation, Vaccination & Diagnostics",
    clinicType: "Clinic",
    category: "Veterinary Care",
    rating: 4.8,
    reviewCount: 289,
    address:
      "MacArthur Highway, Barangay Dolores, City of San Fernando, Pampanga, Philippines",
    distanceKm: 11.4,
    openingHours: "8 Am - 7 Pm",
    phone: "+63 998 211 1144",
    description:
      "San Fernando Animal Care Center provides preventive consultations, vaccination programs, and diagnostics with a patient-first approach for dogs and cats.",
    latitude: 15.025239,
    longitude: 120.691412,
    media: createDefaultClinicMedia("vet-clinic-2"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: true,
    isRecommended: true,
  },
  {
    id: "vet-clinic-3",
    name: "Angeles Pet Wellness Hub",
    services: "Veterinary Clinic, Surgery & Pet Pharmacy",
    clinicType: "Clinic",
    category: "Pet Wellness",
    rating: 4.7,
    reviewCount: 412,
    address:
      "Friendship Highway, Anunas, Angeles City, 2009 Pampanga, Philippines",
    distanceKm: 19.1,
    openingHours: "9 Am - 8 Pm",
    phone: "+63 917 400 3510",
    description:
      "Angeles Pet Wellness Hub offers consultation, treatment planning, surgery support, and pharmacy access to help pets recover and stay healthy.",
    latitude: 15.151652,
    longitude: 120.587928,
    media: createDefaultClinicMedia("vet-clinic-3"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: true,
    isRecommended: false,
  },
  {
    id: "vet-clinic-4",
    name: "Mabalacat Companion Animal Hospital",
    services: "Emergency Care, Confinement & Laboratory Services",
    clinicType: "Hospital",
    category: "Animal Hospital",
    rating: 4.9,
    reviewCount: 367,
    address:
      "McArthur Highway, Dau, Mabalacat City, 2010 Pampanga, Philippines",
    distanceKm: 22.2,
    openingHours: "24 Hours",
    phone: "+63 915 630 1188",
    description:
      "Mabalacat Companion Animal Hospital supports urgent and advanced cases with emergency response, confinement options, and laboratory services.",
    latitude: 15.206032,
    longitude: 120.576395,
    media: createDefaultClinicMedia("vet-clinic-4"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: true,
    isRecommended: true,
  },
  {
    id: "vet-clinic-5",
    name: "Mexico Animal Wellness Clinic",
    services: "Vaccination, Deworming & Preventive Health Checks",
    clinicType: "Clinic",
    category: "Preventive Care",
    rating: 4.8,
    reviewCount: 254,
    address: "Santo Domingo, Mexico, 2021 Pampanga, Philippines",
    distanceKm: 21.5,
    openingHours: "8 Am - 6 Pm",
    phone: "+63 919 885 3321",
    description:
      "Mexico Animal Wellness Clinic focuses on preventive healthcare, parasite control, and routine wellness checks for companion animals.",
    latitude: 15.06365,
    longitude: 120.719379,
    media: createDefaultClinicMedia("vet-clinic-5"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: false,
    isRecommended: true,
  },
  {
    id: "vet-clinic-6",
    name: "Guagua Pet Care & Grooming Center",
    services: "Veterinary Consultation, Grooming & Pet Supplies",
    clinicType: "Clinic",
    category: "Pet Services",
    rating: 4.6,
    reviewCount: 198,
    address: "San Nicolas 1st, Guagua, 2003 Pampanga, Philippines",
    distanceKm: 18.7,
    openingHours: "9 Am - 7 Pm",
    phone: "+63 916 441 8802",
    description:
      "Guagua Pet Care & Grooming Center blends daily veterinary consultation with grooming care and pet supply essentials in one location.",
    latitude: 14.964889,
    longitude: 120.632827,
    media: createDefaultClinicMedia("vet-clinic-6"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: false,
    isRecommended: false,
  },
  {
    id: "vet-clinic-7",
    name: "Magalang Vet Home Service & Clinic",
    services: "House Calls, Preventive Care & General Consultation",
    clinicType: "Clinic",
    category: "Home Service",
    rating: 4.5,
    reviewCount: 144,
    address: "San Pablo, Magalang, 2011 Pampanga, Philippines",
    distanceKm: 30.6,
    openingHours: "8 Am - 5 Pm",
    phone: "+63 920 710 4820",
    description:
      "Magalang Vet Home Service & Clinic is ideal for pet owners who need both in-clinic treatment and home consultation support.",
    latitude: 15.216109,
    longitude: 120.661752,
    media: createDefaultClinicMedia("vet-clinic-7"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: false,
    isRecommended: false,
  },
  {
    id: "vet-clinic-8",
    name: "Apalit Pet Health Corner",
    services: "Consultation, Vaccination & Pet Pharmacy",
    clinicType: "Store",
    category: "Pet Pharmacy",
    rating: 4.7,
    reviewCount: 221,
    address: "San Vicente, Apalit, 2016 Pampanga, Philippines",
    distanceKm: 26.3,
    openingHours: "9 Am - 8 Pm",
    phone: "+63 917 778 0922",
    description:
      "Apalit Pet Health Corner offers core veterinary needs including consultation, immunization support, and convenient pharmacy access.",
    latitude: 14.952965,
    longitude: 120.768001,
    media: createDefaultClinicMedia("vet-clinic-8"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: true,
    isRecommended: false,
  },
  {
    id: "vet-clinic-9",
    name: "Arayat Animal Care Station",
    services: "Consultation, Diagnostics & Minor Procedures",
    clinicType: "Clinic",
    category: "Animal Care",
    rating: 4.6,
    reviewCount: 173,
    address: "Poblacion, Arayat, 2012 Pampanga, Philippines",
    distanceKm: 33.9,
    openingHours: "8 Am - 6 Pm",
    phone: "+63 995 222 6650",
    description:
      "Arayat Animal Care Station delivers diagnostic screening and minor procedures with practical treatment plans for companion animals.",
    latitude: 15.15557,
    longitude: 120.769577,
    media: createDefaultClinicMedia("vet-clinic-9"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: false,
    isRecommended: true,
  },
  {
    id: "vet-clinic-10",
    name: "Lubao Pet Wellness Point",
    services: "Wellness Exams, Vaccines & Nutritional Advice",
    clinicType: "Clinic",
    category: "Pet Wellness",
    rating: 4.7,
    reviewCount: 205,
    address: "Santo Tomas, Lubao, 2005 Pampanga, Philippines",
    distanceKm: 24.2,
    openingHours: "9 Am - 7 Pm",
    phone: "+63 928 300 4170",
    description:
      "Lubao Pet Wellness Point focuses on complete wellness exams, vaccination reminders, and practical nutrition guidance for pets.",
    latitude: 14.938205,
    longitude: 120.596592,
    media: createDefaultClinicMedia("vet-clinic-10"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: true,
    isRecommended: true,
  },
  {
    id: "vet-clinic-11",
    name: "Sta. Rita Veterinary Services",
    services: "General Practice, Grooming & Pet Supplies",
    clinicType: "Clinic",
    category: "General Practice",
    rating: 4.4,
    reviewCount: 119,
    address: "Poblacion, Santa Rita, 2002 Pampanga, Philippines",
    distanceKm: 16.8,
    openingHours: "8 Am - 5 Pm",
    phone: "+63 918 551 2901",
    description:
      "Sta. Rita Veterinary Services provides day-to-day general practice, grooming sessions, and essential pet products for local pet owners.",
    latitude: 15.001957,
    longitude: 120.615132,
    media: createDefaultClinicMedia("vet-clinic-11"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: false,
    isRecommended: false,
  },
  {
    id: "vet-clinic-12",
    name: "Clark Fur Family Vet Clinic",
    services: "Checkups, Surgery Referrals & Pet Travel Requirements",
    clinicType: "Clinic",
    category: "Family Vet Clinic",
    rating: 4.9,
    reviewCount: 338,
    address:
      "Clark Freeport Zone, Angeles City, Pampanga, Philippines",
    distanceKm: 21.3,
    openingHours: "9 Am - 8 Pm",
    phone: "+63 936 774 1010",
    description:
      "Clark Fur Family Vet Clinic supports pets through checkups, surgical referral coordination, and travel requirement documentation.",
    latitude: 15.173809,
    longitude: 120.54887,
    media: createDefaultClinicMedia("vet-clinic-12"),
    image: VETERINARY_ASSETS.clinicPlaceholder,
    logo: VETERINARY_ASSETS.clinicPlaceholder,
    isPopular: true,
    isRecommended: true,
  },
];

const VETERINARY_CLINICS_BY_ID = new Map(
  VETERINARY_CLINICS_MOCK_DATA.map((clinic) => [clinic.id, clinic] as const),
);

export const getVeterinaryClinicById = (clinicId: string) =>
  VETERINARY_CLINICS_BY_ID.get(clinicId) ?? null;
